name: iPhoneArt
favicon: null
layout_spectrum: 0
typography_spectrum: 0.23838
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a15a2c'
    - '#2f2b2a'
    - '#712d16'
    - '#d0944e'
    - '#ead6a3'
  brandStrength: 0.5115020456723869
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
