name: iPhoneArt
favicon: null
layout_spectrum: 0.5853454368188977
typography_spectrum: 0.057758231181651354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5115020456723869
  lightness: 0.4704713311512023
  saturation: 0.8396335495635867
  rhythmicContrast: 0.6924859373830259
purpose: []
