name: iPhoneArt
favicon: null
layout_spectrum: 0.15653
typography_spectrum: 0.29618
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1b17'
    - '#425d72'
    - '#ac3d32'
    - '#8c7a4c'
    - '#6b9b9b'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
